# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# @see https://github.com/marketplace/actions/vuepress-deploy

name: GitHub Pages Actions
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: node-version
        uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: dist
